name: fuel_it
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.3
  kr_paginate_firestore: ^1.0.4
  flutter_pagewise: ^2.0.4
  flutter_lints: ^2.0.0
  dots_indicator: ^3.0.0
  google_fonts: ^6.1.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  provider: ^6.1.1
  geolocator: ^10.1.0
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.2.0
  carousel_slider: ^4.2.1
  dio: ^5.4.0
  flutter_polyline_points: ^2.0.0
  flutter_rating_bar: ^4.0.1
  firebase_pagination: ^3.1.0
  infinite_listview: ^1.1.0
  persistent_bottom_nav_bar: ^5.0.2
  bottom_nav_bar: ^1.0.3
  curved_navigation_bar: ^1.0.3
  map_launcher: ^3.1.0
  pdf: ^3.10.8
  slide_switcher: ^1.1.2
  geocoding: ^3.0.0
  razorpay_flutter: ^1.3.6
  flutter_switch: ^0.3.2
  toggle_switch: ^2.3.0
  lite_rolling_switch: ^1.0.1
  flutter_advanced_switch: ^3.1.0
dev_dependencies:
  animated_toggle_switch: ^0.8.2
  crypto: ^3.0.3
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.2.4
  
assets:
    - assets/

 

flutter:

  uses-material-design: true
