name: fuel_it
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dots_indicator: ^3.0.0
  google_fonts: ^6.1.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  provider: ^6.1.1
  geolocator: ^10.1.0
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.2.0
  carousel_slider: ^4.2.1

flutter:

  uses-material-design: true
